### PR TITLE
Create py_library target for use by drake install

### PR DESCRIPTION
**Pull request by jamiesnape**
PTAL @sammy-tri.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/optitrack-driver/4)

### CODE REVIEW

**Comment by sammy-tri** [comment]
I recall we talked the other day about the issue where unless you explicitly build `@optitrack_driver` in drake,  you wind up with a broken `bazel-bin/external/optitrack_driver/src/optitrack_client` since the `optitrack_client.runfiles` directory is missing.  Is this related to that issue?  

Or is this related to the fact that the installed broken (no runfiles) version of optitrack_client winds up in `lib/python2.7/site-packages/optitrack/optitrack_client`?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/optitrack-driver/4#-:-Kx9_f68pkrJlue6BfFN:bhuj2zp)*

**Comment by jamiesnape** [comment]
The latter. The former is a little more mysterious and I am still looking into that,

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/optitrack-driver/4#-:-Kx9eYDdmA5G26p-_Qsw:b-2ocyeu)*

**Comment by sammy-tri** [comment]
Nod.   The installed version also currently winds up with no `.runfiles` directory...  I'm guessing that this change is a prerequisite to fixing that?  (this will probably make a lot more sense once I see the drake side of the change...  thanks for indulging me)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/optitrack-driver/4#-:-KxA5UsI7z3_yZmhV7mS:bqbwv7w)*

**Comment by jamiesnape** [comment]
Yes. You will get all the `*.py` files in the install directory `lib/python2.7/site-packages/optitrack` and a non-broken wrapper in `bin` that sets the `PYTHONPATH` correctly and calls `optitrack_client.py` as the bazel wrapper does.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/optitrack-driver/4#-:-KxU8mUjhBj1UpUAVDI6:bheqhqy)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/optitrack-driver/4#-:-Kxi9vorZfGm5hjtQu7P:bnfp4nl)*

**Pull request merged**
